### ISSUE TITLE
Increase customizability of values ​​that can be returned by apiReturnType

### ISSUE THREAD

**Issue by matsudamper** [kobylynskyi/graphql-java-codegen#1167]
# Description
I want to generate the following code
- Need to return CompletableFuture to dispatch DataLoader
- Need to set localContext

DataLoader
```kotlin
fun book(
    id: Long,
    env: DataFetchingEnvironment,
): CompletionStage<DataFetcherResult<Book>> { // here
    val bookNameDataLoader = env.dataLoaderRegistry.getDataLoader<Long, String>("key")
    val bookNameCompletableFuture = bookNameDataLoader.load(id)

    return CompletableFuture.supplyAsync {
        DataFetcherResult.newResult<Book>()
            .localContext("additionalContext")
            .data(
                Book(
                    id = id,
                    name = bookNameCompletableFuture.get(),
                )
            )
            .build()
    }
}
```

The apiReturnType setting does not seem to allow the following to be output. We would like to enable this.
`CompletionStage<DataFetcherResult<T>>`

## **Describe the solution you'd like**
I want to enable the following statements
```
apiReturnType = "java.util.concurrent.CompletionStage<graphql.execution.DataFetcherResult<{{TYPE}}>>"
```

## Other
I can submit the code.
https://github.com/kobylynskyi/graphql-java-codegen/compare/main...matsudamper:graphql-java-codegen:feature/damper/api-return-type-placeholder?expand=1

**Comment by kobylynskyi** [comment]
@matsudamper [your approach](https://github.com/kobylynskyi/graphql-java-codegen/compare/main...matsudamper:graphql-java-codegen:feature/damper/api-return-type-placeholder?expand=1) looks good to me. But can you please add a few unit tests:
* specifying `apiReturnType` with `{{TYPE}}` and checking generated code for APIs that return both type and list of types.
* specifying `apiReturnType` and `apiReturnListType` with `{{TYPE}}` and checking generated code for APIs that return both type and list of types.

**Comment by kobylynskyi** [comment]
@matsudamper can you please add a few unit tests for the functionality you added? Thank you.

**Comment by DobryninVyacheslav** [comment]
Hi everyone!
Can you please tell me how it should work?
When I add `apiReturnType = "java.util.concurrent.CompletableFuture<{{TYPE}}>"`, this is added for all resolvers.
Although I need only for field resolvers, because for `@QueryMapping` Spring does not recognize `CompletableFuture`, only for `SchemaMapping` (this is necessary for the `DataLoader` to work properly)

**Comment by kobylynskyi** [comment]
@DobryninVyacheslav in this case I guess we would need to introduce another property, something like `fieldResolverReturnType`. You would use it instead of `apiReturnType`

**Comment by DobryninVyacheslav** [comment]
Now I tested my code again and found that the problem was not in Spring.
In fact, in the process of testing, I removed the resolver interface, in which there was an annotation @Argument, due to the absence of which nothing worked.
When I returned it, everything worked. I'm sorry I didn't notice this sooner.
However, yes, it would be convenient to have such an option (`fieldResolverReturnType`)
Thank you!

**Comment by DobryninVyacheslav** [comment]
In the end, I came to the conclusion that these settings allow the use of DataLoader and looks like a good solution:
```Kotlin
apiReturnType = "reactor.core.publisher.Mono"
apiReturnListType = "reactor.core.publisher.Flux"
```
For blocking code too. You can use `Mono.fromFuture`, `Flux.fromIterable` and so on.
Therefore, for my case, there is no longer a need for the option `fieldResolverReturnType`, but perhaps it will be useful to someone.
