### ISSUE TITLE
Consider using less general names in example schemas

### ISSUE THREAD

**Issue by benmccann** [kobylynskyi/graphql-java-codegen#134]
I was looking at the [example `QueriesResolver`](https://github.com/kobylynskyi/graphql-java-codegen/blob/master/plugins/gradle/example-server/src/main/java/io/github/kobylynskyi/product/graphql/resolvers/QueriesResolver.java) and saw that it implemented `Query` from `io.github.kobylynskyi`. I wasn't sure what this class was or why I'd need to implement it. Then I think I figured out that it's probably being generated from [the schema](https://github.com/kobylynskyi/graphql-java-codegen/blob/master/plugins/gradle/example-server/src/main/resources/schema.graphqls) which has a query of type `Query`. Perhaps we could call this `ProductQuery` to make it clearer that it's specific to the example schema and not something general that every resolver needs to implement?

**Comment by joffrey-bion** [comment]
Yes, the rationale behind this is that the root GraphQL type's name is `Query` (similarly, the 2 other root types are `Mutation` and `Subscription`).

This is part of the generated API interfaces, which you can opt-out by setting `generateApis` to `false`. This point of using the API interfaces (and implement them from your resolvers) is to ensure at build time that you have implemented all the resolver methods that are required for a proper wiring of your GraphQL library.

Now, about the name, I believe it does make sense to keep it in line with the actual type's name in the schema, but we could provide options to add prefixes/suffixes also for API interfaces (like the ones for model classes).

**Comment by benmccann** [comment]
Oh, right. I see. There actually are already generated queries specific to the fields in the root query (`ProductsQuery`, `ProductByIdQuery`, `ProductsByIdsQuery`). Do you think it's even worth generating the root-level `Query`? I have to imagine that in any real project you're not going to put all your code in one file. I think it'd be more realistic to use these specific queries in the example rather than the root query (sorry I'm new to this and probably using the wrong terminology)

**Comment by joffrey-bion** [comment]
In the code, there is a comment explaining that the reason for generating the `Query` interface with all resolver methods for all fields is because of this issue with Relay: https://github.com/facebook/relay/issues/112

To be honest, the first time I met the codebase, I was actually surprised the other way. I would expect only the main `Query` interface without the per-field ones.

There are 2 reasons for this:
1. if you only have per-field interfaces, and you add new fields to your `Query` type, then you have no way to check at build time that you're missing new resolvers methods. This sort-of defeats the purpose of even implementing these interfaces in the first place.
2. I don't like much treating `Query` differently from other GraphQL types. Other types may have parameterized fields, or even normal fields that require a resolver. For them, we generate a single resolver interface which require you to implement resolvers for all fields that require them.

**Comment by benmccann** [comment]
1) is a good point that I hadn't considered. Thanks for taking the time to respond! Feel free to close this :smile:

**Comment by joffrey-bion** [comment]
@benmccann no problem, you raise good points that are useful to consider 😉 

I will let @kobylynskyi take a look at this and close at he pleases. He's the maintainer of the repo and may have a different opinion about this.

**Comment by kobylynskyi** [comment]
* @benmccann generic `Query` class (having all queries) is generated because somebody can have a pretty small schema with 5-7 queries and it might make sense to `implement Query` instead of `implement FirstQuery, SecondQuery, ThirdQuery, FourthQuery, etc`. It is up to the client to decide which way to go, that's why we are generating both. 

* I think it is a pretty good idea to have `Query` class to be named `QueryResolver` and all `AbcQuery` classes to be named `AbcQueryResolver` classes. But with such minor "improvement" we could brake client implementation. So if we do this, I would agree with @joffrey-bion and introduce config options for configuring prefix/suffix for generated apps. Created #136 for this.

@benmccann, @joffrey-bion, Thanks for bringing this up. Closing the issue.
