### ISSUE TITLE
Auto-generate generic class prefixes for Query / Mutation based on schema hierarchy

### ISSUE THREAD

**Issue by jyjyj** [kobylynskyi/graphql-java-codegen#142]
In #134, @joffrey-bion raised a very good point about no way to check that resolver implementations are missing with per-field interfaces. This is very important to me as my schema grows (and will possibly be maintained by more than 1 person), and hence I'm thinking of implementing the generic Query instead of per-field as I'm doing currently.

However, for the sake of organisation as my schema is rapidly growing, would it be possible to generate prefixes to the generic Query / Mutation classes automatically based on the organisational hierarchy of the `.graphql `files in `resources`, and additionally have them only encompass the schemas included in their respective directories? I know we can do this currently by creating multiple graphqlcodegentasks, but I can see that being prone to human error. I'm thinking something like:

if `resources` has `folderA` which has some schema e.g. `extend Query { folderAMethod }` and `folderB` which has e.g. `extend Query { folderBMethodX }`, that the generated classes could have a generic interface `folderAQuery` with method `folderAMethod` and `folderBQuery` with `folderBMethod`.

This way, in my implementation, because I would like to have separate implementation classes for `folderA` and `folderB`, I could have the implementation class for `folderA` simply `implements folderAQuery` which would force me to implement `folderAMethod` and similarly for `folderB`.

I do know you can do most of this with multiple codegen tasks, but I thought it would be prone to human error and would be helpful if this were possible. Additionally (correct me if I'm wrong), but even doing so would simply have a generic `Query` in both cases, and that feels non-ideal vs. `folderAQuery` and `folderBQuery`.

Would like to hear your views e.g. if you think it's too minor. Thanks!

**Comment by kobylynskyi** [comment]
@jyjyj Thanks for bringing this up! That's a really nice feature to have, especially in big projects.

I think this request can be split into two different parts:

1. Introduce a configurable enum option that can define a strategy of API classes naming (something like `apiNamePrefixStrategy`) which will have possible values:
   *  **`FILE_NAME_AS_PREFIX`** - will take the filename as a prefix (e.g.: `order-service.graphqls` -> `OrderServiceQuery.java`, `OrderServiceGetOrderByIdQuery.java`)
   * **`FOLDER_NAME_AS_PREFIX`** - will take folder name as a prefix for all API interfaces. 
   * **`CONSTANT`** - (**default**) - `apiNamePrefix` property will be taken into account (which will be empty by default so that it does not break existing clients)
BTW, `apiNamePrefix`/`apiNameSuffix` options will be implemented as part of #136.

2. Introduce a configurable enum option to generate a super-interface (something like `generateApiInterface` which will have possible values:
   * **`INTERFACE_PER_SCHEMA`** - will generate multiple super-interfaces for each graphql file. Taking into account `apiNamePrefixStrategy`. e.g.: `OrderServiceQuery.java`, `ProductServiceQuery.java`, etc.
   * **`SINGLE_INTERFACE`** - (**default**) - will generate a single `Query.java`, `Mutation.java`, `Subscription.java` for all graphqls (in addition to separate interfaces for each query/mutation/subscription)

@jyjyj @joffrey-bion what do you guys think? Sorry if it sounds too complicated, but it will be great to satisfy everyone's needs.

**Comment by jyjyj** [comment]
Hi @kobylynskyi this looks great! If I'm reading it correctly, the **`CONSTANT`** and **`SINGLE_INTERFACE`** are equivalent to the current configuration?

At first glance, I think I would only need up to folder-level configuration in terms of implementing interfaces (I want to implement a single `Query` so as to make sure I have implemented all its member resolvers), and currently I think I'm naming my resolvers pretty ok, so my most immediate desire would probably be for **`INTERFACE_PER_SCHEMA`** (and I assume its associated `apiNamePrefixStrategy`). If I understand you correctly, combining this with **`FOLDER_NAME_AS_PREFIX`** is exactly what I requested for in my OP (please clarify if not!).

Perhaps one addition to **`FOLDER_NAME_AS_PREFIX`** is maybe configuring the root folder of the schema files, e.g. with the `graphqlSchemas` part of the gradle config? Currently I do not set this `graphqlSchemas` in my config as I'm taking all `.graphql` files in my resources folder, but they are actually organised in a further `graphql` folder (i.e. `resources/graphql/XXX.graphql`). If I set the eventual **`FOLDER_NAME_AS_PREFIX`**, I would probably set it as `resources/graphql/folderA/xxx.graphql`, but I would prefer the generated interface to be `folderAQuery` instead of `graphqlFolderAQuery`, if that makes sense - so maybe leveraging the existing `graphqlSchemas` to define the root folder for the **`FOLDER_NAME_AS_PREFIX`** as well.

Thanks for your prompt and comprehensive suggestions! Excited to hear what you guys think, I'm kinda thinking ahead for my project but it's definitely growing rapidly. Furthermore, with a (current plan) single middleware GraphQL layer eventually serving the entire project, some form of organisation would be very helpful. Thanks :)

**Comment by kobylynskyi** [comment]
@jyjyj, correct, **`CONSTANT`** and **`SINGLE_INTERFACE`** is as per the v1.7.2 implementation.

And yes, **`INTERFACE_PER_SCHEMA`** and **`FOLDER_NAME_AS_PREFIX`** is what you asked in the description of this issue.

Regarding **`FOLDER_NAME_AS_PREFIX`** - we need to identify how many folder levels to take into account for the interface suffix. Maybe just take only one-level to be safe. What do you think?

**Comment by jyjyj** [comment]
Hi @kobylynskyi,

> Regarding **`FOLDER_NAME_AS_PREFIX`** - we need to identify how many folder levels to take into account for the interface suffix. Maybe just take only one-level to be safe. What do you think?

Do you mean the number of folder levels from the highest moving down (e.g. from `resources`), or moving up from the schema file itself (would assume the latter)?

If indeed you are referring to the latter (meaning how many layers of parents to take into account for the prefix), then yes I think one layer is good! Perhaps you could also add another configuration variable such as **`NUM_PARENT_LEVELS`** to be used as part of the **`FOLDER_NAME_AS_PREFIX`**, that could maybe be set to default as 1, and be able to take other numeric variables, where perhaps `-1` could indicate take all the way from root? Not sure if that makes sense though.

For me, I think 1 layer works good because how I'm organising my schema files is (1) by module, then (2) by graphql type - meaning if I have modules `A` and `B`, I would do:

- A
  - A_type.graphql
  - A_enum.graphql
  - A_resolver.graphql
- B
  - B_type.graphql

and so on, so a single layer (the `A` and `B`) would be sufficient for me. I guess this could depend on how people are doing for larger projects, as my project is currently only beginning to organise our graphql schemas and this seems to work well for me so far. Thanks!

**Comment by kobylynskyi** [comment]
Will be released in version 2.0.0 this or next week

**Comment by jyjyj** [comment]
@kobylynskyi thanks so much! makes it a lot cleaner :) i don't suppose there's way to not generate all the individual resolver interfaces? XD
