### ISSUE TITLE
Currently we have a graphql schema with case sensitive types and maven-plugin is failing while generating model classes saying file already exisits.

### ISSUE THREAD

**Issue by Teja6028** [kobylynskyi/graphql-java-codegen#650]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Comment by jxnu-liguobin** [comment]
After testing, I found that Java does not support using `class name` and `class Name` at the same package.
My guess is that some operating system files are case independent, so the JVM ignores them after compilation.


In fact, this problem is also related to [that](https://github.com/kobylynskyi/graphql-java-codegen/issues/647) problem, which needs independent package.

**Comment by kobylynskyi** [comment]
As suggested in #647, the solution could be to split the types (having the same name but different case) into different `.graphqls` files and generate those separately. Anyway, I don't there's something else we can do from the codegen side. So closing the issue for now.
