### ISSUE TITLE
model class generation for case sensitive names 

### ISSUE THREAD

**Issue by Teja6028** [kobylynskyi/graphql-java-codegen#651]
Currently we have a graphql schema with case sensitive types and maven-plugin is failing while generating model classes saying file already exisits.

**Solution I think of is**
Generate packages for model classes based on graphql schema that way it won't class on duplicate files.

**Comment by kobylynskyi** [comment]
I @Teja6028 
Could you please provide a sample schema so that we can reproduce the issue? Thanks

**Comment by Teja6028** [comment]
Hi.. Below is the sample schema I was referring to

schema {
    query: Query
}

type Query {
    productById(id: ID!): Product
}

type Product {
    id: ID!
    title: String!
    description: String
    priceDetails: PriceDetails
}

type PriceDetails {
    quantity: String
    rate: Int
    PRICEDETAILS: PRICEDETAILS
}

type PRICEDETAILS {
    PRICEPERITEM: Int
    TOTALPRICE: Int
}

**Comment by jxnu-liguobin** [comment]
In my humble opinion, there is something wrong with this schema design. 😅

**Comment by kobylynskyi** [comment]
Agree with @jxnu-liguobin

**Comment by Teja6028** [comment]
Can you explain me what you think is wrong in the schema.. Is it same types with case sensitivity or anything else? 

But I read Graphql supports case sensitive names..

**Comment by robbertnoordzij** [comment]
I tried your sample schema with the maven plugin on java 11 on a linux machine. This works fine. I suspect that you are using an Windows based system in which filenames are case insensitive.So this is not an issue with the code gen or java, I think. 

However, to me as an engineer the naming does not seem self explanatory. On a glance, I can not see the difference between the `PRICEDETAILS` and `PriceDetails` by just the name of the type.

I would suggest something like:

```
type OrderLine {
    quantity: String
    rate: Int
    pricePerItem: Int
    totalPrice: Int
}
```

Especially since there is no relation between the `pricePerItem` and `totalPrice` without the quantity (which is in the parent).

**Comment by Teja6028** [comment]
Thanks for that @robbertnoordzij

**Comment by yeikel** [comment]
I stumbled into this one

Example types within the same schema 

```
type Hierarchy {

}

type hierarchy {

}
```

I agree with the sentiment that this design is poor, but sadly there is little I can at this point as because the application is in production accepting traffic


> Caused by: java.nio.file.FileAlreadyExistsException: File already exists: /graphql/model/Hierarchy.java

The solution at this point (without a change in schema) is unclear, but I would be happy with some workaround such as append a suffix to the model class 

@kobylynskyi I can create a new issue if that makes more sense
