### ISSUE TITLE
Implement while keeping DataFetcher [Question]

### ISSUE THREAD

**Issue by jyjyj** [kobylynskyi/graphql-java-codegen#73]
Based on my understanding, the APIs generated (query etc.) should be implemented in the desired format, and it returns the output format of the query. I have legacy code that uses (for example) the Java library graphql.schema.DataFetcher<JSONArray> to return the output which is then processed and exposed as the relevant endpoint. 

Is it possible to reuse this DataFetcher, or will I have to completely rewrite the code (not recommended as many others are still using it)? 

If the latter case, what is the recommended way of implementing the endpoint? I have seen the Controller in "https://github.com/kobylynskyi/graphql-java-codegen/blob/master/plugins/gradle/example-client/src/main/java/io/github/kobylynskyi/order/graphql/GraphQLController.java", but I'm not sure how to connect this with my schema and implementation.

Thanks!

**Comment by joffrey-bion** [comment]
Currently, the generated interfaces match the signature expected by [GraphQL Java Tools](https://www.graphql-java-kickstart.com/tools/schema-definition/), which is built on top of the plain GraphQL Java for easier setup (auto wiring and discovery of types).

Using GraphQL Java Tools, you simply have to implement the generated interfaces and register them when creating the GraphQL schema (see the link above).

The goal of generating these interfaces at compile time is to fail the build when there is an inconsistency between the schema and the Java code.

I believe that if you're using GraphQL Java's plain `DataFetcher`, you may also be wiring all your schema manually, right? In this case, I don't believe there is much benefit in actually implementing the generated interfaces.

**Comment by joffrey-bion** [comment]
FYI, here is a simplification of how I created my `GraphQL` instance:

```java
public class GraphQLBuilder {

    private static final Logger logger = LoggerFactory.getLogger(GraphQLBuilder.class);

    private static final String GRAPHQL_RESOURCES_PACKAGE = "graphql";

    private static final Pattern SCHEMAS_REGEX = Pattern.compile(".*\\.graphqls");

    private final List<? extends GraphQLResolver<?>> resolvers;

    private final Collection<Class<?>> typeDictionary;

    public GraphQLBuilder(List<? extends GraphQLResolver<?>> resolvers, Collection<Class<?>> typeDictionary) {
        this.resolvers = resolvers;
        this.typeDictionary = typeDictionary;
    }

    public GraphQL createGraphQL() {
        return GraphQL.newGraphQL(parseSchemaFromResources()).build();
    }

    private GraphQLSchema parseSchemaFromResources() {
        String[] schemas = findSchemasFiles();
        logger.info("Loading {} GraphQL schema files: {}", schemas.length, Arrays.toString(schemas));
        return SchemaParser.newParser()
            .files(schemas)
            .resolvers(resolvers)
            .dictionary(typeDictionary)
            .build()
            .makeExecutableSchema();
    }

    private static String[] findSchemasFiles() {
        Reflections reflections = new Reflections(GRAPHQL_RESOURCES_PACKAGE, new ResourcesScanner());
        return reflections.getResources(SCHEMAS_REGEX).stream().sorted().toArray(String[]::new);
    }
}

```

**Comment by jyjyj** [comment]
Hi Joffrey, thanks a lot for your prompt reply!

For some context:

Yes, currently we are using `DataFetcher`, but due to how we have implemented our stack, it is a manual wiring but I think not the kind that you are thinking of - instead we are simply mapping the API output to the GraphQL output without making much transformation. This means that we have not defined any Java classes to map to our GraphQL schema at all. From what I understand, this was a deliberate decision to minimise the workload on the GraphQL layer, by doing most of the workload on the backend API side, and hence the GraphQL code does not need to write any classes or interfaces.

However, moving forward we foresee that more complicated processing will definitely need to be done on the GraphQL layer, hence we are looking at solutions to automatically map our schema to Java's requirements (e.g. statically-typed classes, as we previously implemented GraphQL in NodeJS which is dynamic).

Correct me if I'm wrong, but as I understand, your abstraction on top of `graphql-java-tools` is to remove the need to define our own Java classes. This aligns with us, as we prefer to move schema-first and wish to not maintain any language-specific things like classes in Java.

Overall:

We are exploring and are open to moving to a schema-first method that still maintains a more stringent code check (e.g. JS -> Java) while not needing to maintain double the amount of code (schema only vs. schema + classes/interfaces).

In more details, our current implementation (Java) after defining our query is:
- creating a GraphQL RuntimeWiring with the list of our dataFetchers
- using GraphQL SchemaGenerator to make an executableSchema with the a/m RuntimeWiring and our schemas
- building a new GraphQL using the a/m generated schema

So:

My main task now is to figure out how to do this using your implementation, presumably without having to wire the RuntimeWiring and the schema files together as the schema files are already being used to generate Java interfaces.

Please correct me if I'm wrong here, but my understanding of your workflow is to 
1) Auto-generate the classes/interfaces with your builder (I have defined both an API and MODEL directory in my build.gradle, which I see separates the Enums/Types/Inputs vs. the Queries/Mutations/Subscriptions)
2) Ten further implement the interfaces (query/mutation/subscription etc.)
3) [this is the step that I'm struggling with] Connect the implemented queries with some endpoint connector to expose the endpoint

Apologies for the long wall of text, but hope that provides more context. For me personally, I am not the most familiar with Java overall, hence appreciate any help :) 

Thank you so much!

**Comment by joffrey-bion** [comment]
> it is a manual wiring but I think not the kind that you are thinking of - instead we are simply mapping the API output to the GraphQL output without making much transformation

What I meant was [GraphQL Java's way](https://www.graphql-java.com/documentation/v14/schema/) of defining the relation between the SDL schema and the `DataFetcher`s. Namely, using a `RuntimeWiring` etc, listing all the non-trivial fields manually and associating data fetchers.

> This means that we have not defined any Java classes to map to our GraphQL schema at all. From what I understand, this was a deliberate decision to minimise the workload on the GraphQL layer, by doing most of the workload on the backend API side, and hence the GraphQL code does not need to write any classes or interfaces.

Do you mean that the return types of your `DataFetcher`s are classes that come from your backend API / client library?

> Correct me if I'm wrong, but as I understand, your abstraction on top of graphql-java-tools is to remove the need to define our own Java classes.

This is exactly the goal of this library indeed: removing the need for defining Java classes to match a schema. That being said, it was maybe not the original author's intention to necessarily build on top of `graphql-java-tools` (@kobylynskyi correct me if I'm wrong). I just made some suggestions and changes in this direction because I was using `graphql-java-tools` myself and I needed a bit more from this codegen library to match the classes format expected by it. I also believe that people going schema first have every reason to use `graphql-java-tools`, but we could also add options to generate classes in the format expected by the vanilla GraphQL Java (interfaces for `DataFetcher`s).

> 3. [this is the step that I'm struggling with] Connect the implemented queries with some endpoint connector to expose the endpoint

This is actually web-application-framework specific and has little to do with the codegen library itself. The snippet of code I provided demonstrates how to replace GraphQL Java's `RuntimeWiring` creation by the automated way using GraphQL Java Tools.
What you get from it is just an instance of `GraphQL`, which you can then *manually* use in your endpoint declaration.

Depending on whether you use Spring, Dropwizard or other web application framework, it will vary. For instance, here is something resembling my own dropwizard resource:

```java
import graphql.ExecutionInput;
import graphql.GraphQL;
import java.util.Map;
import javax.ws.rs.Consumes;
import javax.ws.rs.POST;
import javax.ws.rs.Path;
import javax.ws.rs.Produces;
import javax.ws.rs.WebApplicationException;
import javax.ws.rs.core.MediaType;

@Path("/graphql")
@Consumes(MediaType.APPLICATION_JSON)
@Produces(MediaType.APPLICATION_JSON)
public class GraphQLResource {

    private final GraphQL graphQL;

    public GraphQLResource(GraphQL graphQL) {
        if (graphQL == null) {
            throw new IllegalArgumentException("GraphQL object must not be null");
        }
        this.graphQL = graphQL;
    }

    @POST
    public Map<String, Object> graphQL(GraphQLInput graphQLInput) {
        if (graphQLInput == null) {
            throw new WebApplicationException("Missing request body, expected GraphQL input", 400);
        }
        var executionInput = graphQLInput.toInput();
        var executionResult = graphQL.execute(executionInput);
        return executionResult.toSpecification();
    }

    // Standard GraphQL POST request body (JSON)
    public static class GraphQLInput {

        private String operationName;
        private String query;
        private Map<String, Object> variables;

        // getters and setters

        public ExecutionInput.Builder toInput() {
            return ExecutionInput.newExecutionInput(query).variables(variables).operationName(operationName);
        }
    }
}
```

**Comment by jyjyj** [comment]
Hi,

Thanks for your reply. Have a few things to clarify:

Currently, we are using DataFetchers still. I have been able to simply edit the code to allow for your auto-generated classes in the resolvers, but I was thinking that it would be ideal if, once I have generated the classes from the schema, that I can use the resolvers directly into some endpoint without going through the schema again. I think for this part I'm still not quite clear how to do it.

You mentioned that "This is actually web-application-framework specific and has little to do with the codegen library itself. The snippet of code I provided demonstrates how to replace GraphQL Java's RuntimeWiring creation by the automated way using GraphQL Java Tools.
What you get from it is just an instance of GraphQL, which you can then manually use in your endpoint declaration." Could you elaborate more on this? As mentioned above I was thinking that there would be no further need to reference the graphql schema files themselves, but if I'm seeing correctly you are using them still in your GraphQLBuilder example. Also, would this GraphQLBuilder class be directly referenced in your endpoint?

I'm using Springboot and have checked out your [example](https://github.com/kobylynskyi/graphql-java-codegen/blob/master/plugins/gradle/example-server/src/main/java/io/github/kobylynskyi/product/graphql/GraphQLController.java), but am still uncertain about how to actually reference the correct resolver etc. In my current implementation with DataFetcher and RuntimeWiring, the RuntimeWiring is built with the resolver method tagged to a query name, which can be used in the actual GraphQL query. Does something still need to be done for this?

Apologies for the many silly questions, still trying to find my footing with this especially since my previous GraphQL experience is NodeJS-based, which is less strict but hence much simpler. Thank you!

**Comment by joffrey-bion** [comment]
I think we need to be careful about the terms we use here to avoid confusions.
When I say *schema*, I mean the SDL schema files: the GraphQL definition of the types including the root Query type.
When I said "an instance GraphQL", I meant an actual Java instance of the `graphql.GraphQL` class.

The schema files are processed in 2 places:

1. read by `graphql-java-codegen` (from the build plugin) to generate POJO classes and resolver interfaces (for the root query as well as nested field resolvers)
2. read by GraphQL Java or GraphQL Java Tools from the Java code in order to configure and ultimately build a `graphql.GraphQL` instance.

Your own implementation of the resolvers interfaces are registered during 2). These implementations are the ones from which you will temporarily call your old DataResolvers. They are never used directly from the endpoints afterwards, this is the job of the graphQL library.
Actually 2) corresponds to the first snippet I provided with the `GraphQLBuilder`. This is only a helper class to build an instance of `graphql.GraphQL`. It is not directly referenced from the resource (as you can see) because I directly provide the instance of `GraphQL` to its constructor. If you're using Spring, you could even make the produced `GraphQL` a bean that you can then inject in your controllers.

There should be only one endpoint (usually `/graphql`), and it should just use the `graphql.GraphQL` object that you built in 2) to resolve all queries generically. It doesn't have to know about the schema or any of your custom types at all. By the way, some libraries even provide this generic endpoint (or "resource" or "controller") implementation for free.

I'm not sure it's clearer 😞 I hope it is, though.

**Comment by jyjyj** [comment]
Hi, apologies for the late reply!

If my understanding is correct, any eventual endpoint must be served by a `graphql.GraphQL` object, which must be configured by using e.g. GraphQL Java / GraphQL Java Tools by reading the graphql schema files. As for the auto-generated classes, the resolvers are generated as interfaces which must be implemented in some way then read by the a/m `graphql.GraphQL` object (manually in Java code), for example in the DataFetcher -> Provider method suggested by the GraphQL Java tutorial, or some. The eventual GraphQL endpoint then resolves input API calls to the internal code via the `graphql.GraphQL` object through the schema files rather than the Java classes, which are there to provide consistency in writing code rather than actually getting referenced from the endpoint.

I hope my understanding is correct - please correct me wherever wrong; I'm a bit uncertain about the part regarding how the endpoint is resolved to internal code / schema files.

If so, then am I right in saying that the developer must reference the location of the schema files in 2 places: the build.gradle file for the `graphql-java-codegen` as well as wherever it is referenced in the `graphql.GraphQL` object instantiation? 

I think what I was looking for (hoping for) was that the schema files would only need to be used once (in the `graphql-java-codegen` part to generate classes). Is that possible in any way? However, if not so, that is completely fine (small thing); thanks so much for your detailed explanations! 

Wouldn't claim to have understood everything, but hope I have learnt a bit more about GraphQL in Java - thank you! :)

**Comment by joffrey-bion** [comment]
> I'm a bit uncertain about the part regarding how the endpoint is resolved to internal code / schema files.

The GraphQL Java library provides a way to configure a `GraphQL` instance with schemas and resolvers. Once you have this `GraphQL` object, you just have to feed it some graphQL queries and it will resolve them on its own. That's why, from your controllers, you just have to have access to that `GraphQL` instance. The point of GraphQL is that you don't have to implement the calls to your DataFetchers yourself. The library takes care of it.

> If so, then am I right in saying that the developer must reference the location of the schema files in 2 places: the build.gradle file for the `graphql-java-codegen` as well as wherever it is referenced in the `graphql.GraphQL` object instantiation? 

You're right. These 2 places need to read schema files. That being said, you don't have to list actual schema file paths in either place.

For the schema generation part, you don't need `graphqlSchemaPaths` at all. By default, `graphql-java-codegen` will read all `*.graphqls` files from `src/main/resources`, so if you put your files there, you're good to go.
If you want to include schemas in bulk but from another folder, have a look at the `graphqlSchemas` option of the plugin. It contains multiple ways to control how the library will look for schemas (`rootDir`, `recursive` etc.). Look at the README file of the build plugin you're using for more info. 

> I am getting issues in mapping the ExcecutionInput to the GraphQL object.

If you're using Spring, your controllers can map the body of the POST requests to a plain java object, thanks to `@RequestBody`. This is what is done in the [example project here](https://github.com/kobylynskyi/graphql-java-codegen/blob/master/plugins/gradle/example-server/src/main/java/io/github/kobylynskyi/product/graphql/GraphQLController.java#L33).

That being said, `ExecutionInput` is a type from the GraphQL library. I don't like using third-party library objects as models for my request body. That's why in my example above, I used my own `GraphQLInput` class, which I then map to an `ExecutionInput` instance in `toInput`.

Resolving queries is just about passing an `ExecutionInput` to your `GraphQL` instance. If I adapt my own example to Spring, it should be something like:

```java
@PostMapping(
            value = "/graphql",
            consumes = MediaType.APPLICATION_JSON_UTF8_VALUE,
            produces = MediaType.APPLICATION_JSON_UTF8_VALUE)
@ResponseBody
public Map<String, Object> graphQL(@RequestBody GraphQLInput graphQLInput) {
    if (graphQLInput == null) {
        throw new WebApplicationException("Missing request body, expected GraphQL input", 400);
    }
    var executionInput = graphQLInput.toInput();
    var executionResult = graphQL.execute(executionInput);
    return executionResult.toSpecification();
}
```

**Comment by joffrey-bion** [comment]
Also, please note that most of these concepts have nothing to do with this codegen library.
If some of this is still unclear, you should take a look at the GraphQL Java documentation and the GraphQL Java Tools library documentation as well. It will probably clarify how the different pieces work together.

Once you have a good understanding of all of that, you will realize that some part of the Java code you have to write only depends on your schema and can be generated (the data models), and some parts have to fulfill a contract that depend on the library you use and on your schema, so their interfaces can be generated (the resolvers interfaces).
That's where this codegen library comes in, just to save some typing and ensure everything is consistent between Java and the schema.
However, all the execution-related part is still 100% done by the other libraries, the wiring still has to be done as documented in the libraries you're using, and the implementation of your endpoint also should be done like you would do without the java codegen lirbary.

**Comment by jyjyj** [comment]
Hi @joffrey-bion, thanks for your comprehensive reply. I'm still taking time to try and fully understand what you have explained. Thanks a lot for your patience with someone not familiar with the subject matter :)

One question I do have regarding implementation is: based on your reply [here](https://github.com/kobylynskyi/graphql-java-codegen/issues/73#issuecomment-614592088) and others, as well as from my own reading of the `graphql-java-tools`, the graphQL builder needs to take in a list of `GraphQLResolvers`, and you mention that we can simply feed in the implementations of the interfaces generated by this library `graphql-java-codegen`. Perhaps I'm not too clear on explicitly how the `GraphQLResolvers `are implemented in the codegen, so how would I feed in the associated resolvers to the builder?

For example, I have a class `Implementations.java` that implements the generated interfaces. The implemented methods are of various types, so how would you include them all into a `List `that extends the required `GraphQLResolver` type in order to feed the actual graphQL object builder?

Thank you again!

**Comment by jyjyj** [comment]
Managed to resolve the above ^. I'll try and work on the REST controller separately. Thanks a lot again @joffrey-bion!
