### ISSUE TITLE
hierarchical organisation of models / apis

### ISSUE THREAD

**Issue by jyjyj** [kobylynskyi/graphql-java-codegen#96]
Hi, not sure if this is related to the support for extensions (#81), but as our graphql schemas grow and we are using different files to maintain some organisation, would it be possible to have some form of organisation for the generated model and API files as well? Just a little thing as my model and api (especially api) folders are probably going to grow drastically, so would like to organise the files inside. Thank you!

**Comment by kobylynskyi** [comment]
@jyjyj 
As of now, the only level of putting APIs/models into separate folders is via configs `apiPackageName` / `modelPackageName`.
Do you have any suggestions on how to organize files in some other way?

**Comment by jyjyj** [comment]
Hi @kobylynskyi, do you think keeping the same structure as the hierarchy in the `resources` folder be feasible?

For example (I don't know if there's a best practice for this, but this seems to work decently for me), I have organised my schema by modules, then further by type/enum vs. resolvers (query/mutation/sub), meaning my resources folder looks like (after you guys support multiple files and extends):

`
resources
  > graphl
    > module1_type.graphqls
    > module1_resolvers.graphqls
    > module2_type.graphqls
    > module2_resolvers.graphqls
`

I was thinking of organising my API and Model folders in the same way:

`
modelFolder
  > module1_type
  > module2_type
apiFolder
  > module1_resolvers
  > module2_resolvers
`

so perhaps an inference of the file structure of the `resources folder` and keeping a similar name less the `.graphqls` extension. But that's just my first thought!

**Comment by kobylynskyi** [comment]
Hey @jyjyj 
Thanks for your input.
There are still some questions with this approach:
What if ‘type X’ is in ‘folder/file’ and ‘extend type X’ is in ‘folder2/file2’. Should the class for X then go to folder or folder2? There can be multiple extensions across multiple folders/files.


But anyway, as of now you can do such structure (but only if schemas are **completely independent** from each other) by creating a separate graphqlCodegen tasks for the set of schemas.
You can refer to the example configuration here:
https://github.com/kobylynskyi/graphql-java-codegen/blob/master/plugins/gradle/example-client/build.gradle

**Comment by joffrey-bion** [comment]
@kobylynskyi I completely agree with all your points and concerns. Regarding the cross-folder type extensions, we could decide to forbid them (by calling the core library on each folder independently, like we would do by declaring independent plugin executions) or decide that the base declaration of the type defines the place where it should land.

@jyjyj at first I was hoping for the same feature, but then I decided to not be too concerned about it because GraphQL itself doesn't have the concept of namespaces (there has been some discussions about it, but nothing for now). Since your schema can't be namespaced, I guess it just follows that we should keep the same idea in the code: a single package for all types.
It makes sense to be able to declare a separate package for APIs like type resolvers, but for the types themselves I believe it won't bring much value.

**Comment by jyjyj** [comment]
Hi @kobylynskyi @joffrey-bion, noted your points, and think I agree it would be better to follow the specs for now. Hopefully they do release something sensible in the future, as the schema organisation does get a bit messy. Thanks! Closing this issue
